const OpenAI = require('openai');
const { readFileSync } = require('fs');

require('dotenv').config();
CREDENTIALS = process.env.OPENAI_KEY;
const openai = new OpenAI({apiKey:CREDENTIALS});


/**
 * 
 * @param {string} bottle_text text on the medical bottle
 * @param {string} prompt_engineering give it a prompt based on what question we wanna ask about it
 * @returns response from gpt3.5turbo
 */
async function basic_query(bottle_text, prompt_engineering) {

    const response = await openai.chat.completions.create({
        messages: [ { "role": "system", "content": "You are a medical assistant." },
                    { "role": "user", "content": prompt_engineering + "\n" + bottle_text }
        ],
        model: "gpt-3.5-turbo",
    });

    // const response = await openai.chat.completions.create({
    //     model: 'gpt-3.5-turbo',
    //     prompt: prompt_engineering + "\n" + bottle_text
    // });
    return response['choices'][0].message.content;
};

/**
 * 
 * @param {string} bottle_text text on medical bottle
 * @returns response from gpt3.5turbo, where prompt_engineering is autogenerated with default message
 */
async function bottle_query(bottle_text) {
    const prompt_engineering = "The following is the label of a medicinal bottle or product. Explain what this medication is used for and any important information about its usage."
    return basic_query(bottle_text,prompt_engineering);
};


async function main() {
    // const completion = await openai.chat.completions.create({
    //     messages: [{ "role": "system", "content": "You are a helpful assistant." },
    //     { "role": "user", "content": "Who won the world series in 2020?" },
    //     { "role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020." },
    //     { "role": "user", "content": "Where was it played?" }],
    //     model: "gpt-3.5-turbo",
    // });

    console.log(await bottle_query("Compare to active ingredient in Extra Strength Tylenol® Capletst extra strength acetaminophen caplets , 500 mg pain reliever / fever reducer for adults NDC 11673-838-50 TAMPEREVIDE Drug Fath Active ingredien up & up ACTUAL SIZE 500 CAPLETS 500 CAPLETS ** - 500 mg.each ( ** CAPSULE - SHAPED TABLETS ) Acetaminophen Uses e pains due to backache toothache premenst temporani Warnings Liver warning Severe liver more than d maximum da containing A drinks every da skin red It a skin medin help right "));
}
// main();
